pipeline {
    agent none
    stages {
        stage('Pull code') {
            agent any
            steps {
                git 'https://github.com/aabramenko/selenium-framework-skeleton.git'
            }
        }
        stage('Build Image') {
            agent none
            steps {
                script {
                	app = docker.build("alekseiabramenko/selenium-test-environment", "-f docker/Dockerfile .")
                }
            }
        }
        stage('Push Image') {
            agent none
            steps {
                script {
			        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
			        	app.push("${BUILD_NUMBER}")
			            app.push("latest")
			        }
                }
            }
        }
    }
}