pipeline {
    agent none
    stages {
    	stage("Pull code") {
    		steps {
    			git checkout master
    			git pull
    		}
    	}
        stage('Build Image') {
            steps {
                script {
                	app = docker.build("alekseiabramenko/selenium-test-environment", "-f docker/Dockerfile .")
                }
            }
        }
        stage('Push Image') {
            steps {
                script {
			        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
			        	app.push("${BUILD_NUMBER}")
			            app.push("latest")
			        }
                }
            }
        }
    }
}