name: run without docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: run tests
      run: mvn test -DSUITE=test-suite.xml -DHEADLESS=true -DBROWSER=chrome -DGRID=false
